### ISSUE TITLE
可否增加上传COM口选择？

### ISSUE THREAD

**Issue by Whitolf** [yunyizhi/ESP-IDF-for-Clion#2]
可否增加一个上传COM口选择选项？

**Comment by yunyizhi** [comment]
已经发布0.3.1到插件市场
https://plugins.jetbrains.com/plugin/23886-esp-idf/versions/stable/594320 

![image](https://github.com/user-attachments/assets/d9bd279d-7a2c-4122-9807-e75298894c7e)

[文档](https://yunyizhi.github.io/ESP-IDF-for-Clion/settings.html#-8qipzn_7)
