### ISSUE TITLE
是否增加串口选择，烧录波特率选择，以及调试波特率选择

### ISSUE THREAD

**Issue by jinsc123654** [yunyizhi/ESP-IDF-for-Clion#5]
针对这些东西，可以优先使用idf自带的环境变量
例如
IDF_TARGET=esp32s3;ESPPORT=/dev/ttyACM0;ESPBAUD=2000000;MONITORBAUD=921600;
上述环境变量均可使用IDF命令查询到
![image](https://github.com/user-attachments/assets/ea61c3ec-b060-4fd8-89cf-49e0bd907a11)
插件需要做的就是解析.idea中的配置，路径可以使用$ProjectFileDir$/.idea/workspace.xml搜索
![image](https://github.com/user-attachments/assets/a916cafa-c93d-4dd0-a2f2-2ee0587f1d49)

**Comment by yunyizhi** [comment]
已经发布0.3.1到插件市场
https://plugins.jetbrains.com/plugin/23886-esp-idf/versions/stable/594320 

![image](https://github.com/user-attachments/assets/d9bd279d-7a2c-4122-9807-e75298894c7e)

 <h3><a href="https://yunyizhi.github.io/ESP-IDF-for-Clion/settings.html#-8qipzn_7">文档</a></h3>

**Comment by jinsc123654** [comment]
这个版本太高了，Ubuntu下单clion最新只能到24.1.5
[image: image.png]

云逸之 ***@***.***> 于2024年8月29日周四 09:28写道：

**Comment by jinsc123654** [comment]
> 已经发布0.3.1到插件市场 https://plugins.jetbrains.com/plugin/23886-esp-idf/versions/stable/594320
> 
> ![image](https://private-user-images.githubusercontent.com/64545732/362499764-d9bd279d-7a2c-4122-9807-e75298894c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTc5ODMsIm5iZiI6MTcyNDg5NzY4MywicGF0aCI6Ii82NDU0NTczMi8zNjI0OTk3NjQtZDliZDI3OWQtN2EyYy00MTIyLTk4MDctZTc1Mjk4ODk0YzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDAyMTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NWM3MDYwODNkYmQyZDBjODFmZmU5MDc2MjE2Njg3YzI0MWU0NWM5MjNiNjYyYmY5YTU0NjQwOTNlN2ZkNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2aA1a6H-FStiBtTfgtbUYMgDxa_eDmoW1ZUZghHq7dg)
> 
> ### [文档](https://yunyizhi.github.io/ESP-IDF-for-Clion/settings.html#-8qipzn_7)

我有个疑问，就是你的插件为什么不能继续使用idf.py build编译一半的工程，你的插件编译出来的内容和官方命令行一致吗
![image](https://github.com/user-attachments/assets/12d9578f-06a7-40b5-a173-3cb0f0ccf19e)

**Comment by yunyizhi** [comment]
> > 已经发布0.3.1到插件市场 https://plugins.jetbrains.com/plugin/23886-esp-idf/versions/stable/594320
> > ![image](https://private-user-images.githubusercontent.com/64545732/362499764-d9bd279d-7a2c-4122-9807-e75298894c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTc5ODMsIm5iZiI6MTcyNDg5NzY4MywicGF0aCI6Ii82NDU0NTczMi8zNjI0OTk3NjQtZDliZDI3OWQtN2EyYy00MTIyLTk4MDctZTc1Mjk4ODk0YzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDAyMTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NWM3MDYwODNkYmQyZDBjODFmZmU5MDc2MjE2Njg3YzI0MWU0NWM5MjNiNjYyYmY5YTU0NjQwOTNlN2ZkNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2aA1a6H-FStiBtTfgtbUYMgDxa_eDmoW1ZUZghHq7dg)
> > ### [文档](https://yunyizhi.github.io/ESP-IDF-for-Clion/settings.html#-8qipzn_7)
> 
> 我有个疑问，就是你的插件为什么不能继续使用idf.py build编译一半的工程，你的插件编译出来的内容和官方命令行一致吗 ![image](https://private-user-images.githubusercontent.com/53360341/362508978-12d9578f-06a7-40b5-a173-3cb0f0ccf19e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTg4NzQsIm5iZiI6MTcyNDg5ODU3NCwicGF0aCI6Ii81MzM2MDM0MS8zNjI1MDg5NzgtMTJkOTU3OGYtMDZhNy00MGI1LWExNzMtM2NiMGYwY2NmMTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDAyMjkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZTU3NTEyY2I4MzEyYzZmYmVlOWY0ZDI0NTg3ODAyMTM3YjA3NzQ2YWNkNDk2OWUyMjYyZGM1NzM4OTdiYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4-2qGcFrJLNpe1l_xg-zYiMpA-QuW_WL_rLr8nHQPYU)

命令就是这个任务的第一行，也是直接调用的idf.py 可能是Toolchain的用的cmake和idf用的cmake的区别.

**Comment by jinsc123654** [comment]
> > > 已经发布0.3.1到插件市场 https://plugins.jetbrains.com/plugin/23886-esp-idf/versions/stable/594320
> > > ![image](https://private-user-images.githubusercontent.com/64545732/362499764-d9bd279d-7a2c-4122-9807-e75298894c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTc5ODMsIm5iZiI6MTcyNDg5NzY4MywicGF0aCI6Ii82NDU0NTczMi8zNjI0OTk3NjQtZDliZDI3OWQtN2EyYy00MTIyLTk4MDctZTc1Mjk4ODk0YzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDAyMTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NWM3MDYwODNkYmQyZDBjODFmZmU5MDc2MjE2Njg3YzI0MWU0NWM5MjNiNjYyYmY5YTU0NjQwOTNlN2ZkNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2aA1a6H-FStiBtTfgtbUYMgDxa_eDmoW1ZUZghHq7dg)
> > > ### [文档](https://yunyizhi.github.io/ESP-IDF-for-Clion/settings.html#-8qipzn_7)
> > 
> > 
> > 我有个疑问，就是你的插件为什么不能继续使用idf.py build编译一半的工程，你的插件编译出来的内容和官方命令行一致吗 ![image](https://private-user-images.githubusercontent.com/53360341/362508978-12d9578f-06a7-40b5-a173-3cb0f0ccf19e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTg4NzQsIm5iZiI6MTcyNDg5ODU3NCwicGF0aCI6Ii81MzM2MDM0MS8zNjI1MDg5NzgtMTJkOTU3OGYtMDZhNy00MGI1LWExNzMtM2NiMGYwY2NmMTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDAyMjkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZTU3NTEyY2I4MzEyYzZmYmVlOWY0ZDI0NTg3ODAyMTM3YjA3NzQ2YWNkNDk2OWUyMjYyZGM1NzM4OTdiYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4-2qGcFrJLNpe1l_xg-zYiMpA-QuW_WL_rLr8nHQPYU)
> 
> 命令就是这个任务的第一行，也是直接调用的idf.py 可能是Toolchain的用的cmake和idf用的cmake的区别.
![image](https://github.com/user-attachments/assets/11b29c91-c372-4b54-ae98-02e2c73a37e4)

这是我写的shell脚本，Ubuntu可以注册成外部工具
他就是调用命令行的东西，这个脚本编译一半的东西可以被clion 的构建指令继续编译
[clion_idf_terminal_build.txt](https://github.com/user-attachments/files/16791581/clion_idf_terminal_build.txt)
这里再提一句，就是你的IDF插件编译终端，没有警告和错误颜色标识以及跳转超链接，如下图
![image](https://github.com/user-attachments/assets/7356575f-9910-4b26-8b29-b50efea9309e)

**Comment by yunyizhi** [comment]
> > > > 已经发布0.3.1到插件市场 https://plugins.jetbrains.com/plugin/23886-esp-idf/versions/stable/594320
> > > > ![image](https://private-user-images.githubusercontent.com/64545732/362499764-d9bd279d-7a2c-4122-9807-e75298894c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTc5ODMsIm5iZiI6MTcyNDg5NzY4MywicGF0aCI6Ii82NDU0NTczMi8zNjI0OTk3NjQtZDliZDI3OWQtN2EyYy00MTIyLTk4MDctZTc1Mjk4ODk0YzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDAyMTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NWM3MDYwODNkYmQyZDBjODFmZmU5MDc2MjE2Njg3YzI0MWU0NWM5MjNiNjYyYmY5YTU0NjQwOTNlN2ZkNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2aA1a6H-FStiBtTfgtbUYMgDxa_eDmoW1ZUZghHq7dg)
> > > > ### [文档](https://yunyizhi.github.io/ESP-IDF-for-Clion/settings.html#-8qipzn_7)
> > > 
> > > 
> > > 我有个疑问，就是你的插件为什么不能继续使用idf.py build编译一半的工程，你的插件编译出来的内容和官方命令行一致吗 ![image](https://private-user-images.githubusercontent.com/53360341/362508978-12d9578f-06a7-40b5-a173-3cb0f0ccf19e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTg4NzQsIm5iZiI6MTcyNDg5ODU3NCwicGF0aCI6Ii81MzM2MDM0MS8zNjI1MDg5NzgtMTJkOTU3OGYtMDZhNy00MGI1LWExNzMtM2NiMGYwY2NmMTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDAyMjkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZTU3NTEyY2I4MzEyYzZmYmVlOWY0ZDI0NTg3ODAyMTM3YjA3NzQ2YWNkNDk2OWUyMjYyZGM1NzM4OTdiYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4-2qGcFrJLNpe1l_xg-zYiMpA-QuW_WL_rLr8nHQPYU)
> > 
> > 
> > 命令就是这个任务的第一行，也是直接调用的idf.py 可能是Toolchain的用的cmake和idf用的cmake的区别.
> > ![image](https://private-user-images.githubusercontent.com/53360341/362522294-11b29c91-c372-4b54-ae98-02e2c73a37e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MDQyNjYsIm5iZiI6MTcyNDkwMzk2NiwicGF0aCI6Ii81MzM2MDM0MS8zNjI1MjIyOTQtMTFiMjljOTEtYzM3Mi00YjU0LWFlOTgtMDJlMmM3M2EzN2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDAzNTkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzM2ZhYTdkMDgxYTI0ODM5OTg4ZGM1N2RhODBiMTgyODdiNzFlNmVlM2EyOTUwNTMxNGU2ZTg1YzJjZWFjOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hjdYCF3wNlrfGfS6XaScdjySCJ4qGSjNXDFs99H53nU)
> 
> 这是我写的shell脚本，Ubuntu可以注册成外部工具 他就是调用命令行的东西，这个脚本编译一半的东西可以被clion 的构建指令继续编译 [clion_idf_terminal_build.txt](https://github.com/user-attachments/files/16791581/clion_idf_terminal_build.txt) 这里再提一句，就是你的IDF插件编译终端，没有警告和错误颜色标识以及跳转超链接，如下图 ![image](https://private-user-images.githubusercontent.com/53360341/362523808-7356575f-9910-4b26-8b29-b50efea9309e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MDQyNjYsIm5iZiI6MTcyNDkwMzk2NiwicGF0aCI6Ii81MzM2MDM0MS8zNjI1MjM4MDgtNzM1NjU3NWYtOTkxMC00YjI2LThiMjktYjUwZWZlYTkzMDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDAzNTkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNTg2NzYxM2U5YjUyYWI4YzZkZjQ4ZTA1ZDY3Nzg4ZTQyMWM1NTlkZTBmZDhkZTIyYmQzYmRhZmQ2MTc5MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wTaAJtcSGvVAWwMlhCpZbK-jhaFayBw1S3i57bzIvTw)

命令树上的build失败，是可以通过树上clean reconfig相关操作解决的。或者新建项目后直接点击flash and monitor节点，这个节点是使用终端的命令，使用终端执行idf.py比只通过直接起bash进程调用idf.py看起来是成功率会高。

**Comment by bcdax110** [comment]
> 已经发布0.3.1到插件市场 https://plugins.jetbrains.com/plugin/23886-esp-idf/versions/stable/594320
> 
> ![image](https://private-user-images.githubusercontent.com/64545732/362499764-d9bd279d-7a2c-4122-9807-e75298894c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NDE5NjEsIm5iZiI6MTcyODg0MTY2MSwicGF0aCI6Ii82NDU0NTczMi8zNjI0OTk3NjQtZDliZDI3OWQtN2EyYy00MTIyLTk4MDctZTc1Mjk4ODk0YzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDE3NDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmOTgyZmZhYmI1YjU3NDZlNGRhNmI3MzRiN2IyZTUyZGZjMDkwNzBkOGUxMGJiZWE1NGY5NDY2NWRlN2FkNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IfWEuHUiZHS4rBtWOvB9FbO6ur_MTuvIv6YXYkfl_ww)
> 
> ### [文档](https://yunyizhi.github.io/ESP-IDF-for-Clion/settings.html#-8qipzn_7)

这个选项设计还是有一点小问题，建议加入一个可以手动输入的框，还有下拉菜单添加选项76800，手头上的ESP8684 WROOM 01C H2 在没有烧录的时候默认波特率是76800（试了好久，都怀疑是不是硬件有问题了 掀桌.png）

**Comment by jinsc123654** [comment]
我已经不在使用本插件了，后续更新，我也没有尝试
