### ISSUE TITLE
esp-idf v4.4.8, 新建项目，无芯片型号选择

### ISSUE THREAD

**Issue by gonboy** [yunyizhi/ESP-IDF-for-Clion#6]
如题

**Comment by yunyizhi** [comment]
0.3.2 支持 创建时 target 选择 兼容242 以上的clion 
![image](https://github.com/user-attachments/assets/f99e9d15-a588-4595-aa13-7b3d73831ec4)

**Comment by gonboy** [comment]
测试OK
